/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Achivements are now available": "成就现已可用",
    "Add an easy tutorial": "添加一个简单的教程",
    "Added a Reset Game button": "添加了重置游戏按钮",
    "Added Power Ups!": "添加电源UPS！",
    "Additional energies added": "添加了额外的能源",
    "Air Bender": "空气弯管机",
    "Anti-Being": "反存在",
    "Balancing Prices": "平衡价格",
    "Black per click:": "黑色每次点击：",
    "Black per sec:": "黑色每秒：",
    "Blue per click:": "蓝色每次点击：",
    "Blue per sec:": "每秒蓝色：",
    "Convert Rate (Convert by clicking the energy square to the left)": "转换率（通过单击左侧的能源方块进行转换）",
    "Convert rate added under stats": "在统计数据下添加转换率",
    "copyright 2014": "版权所有 2014",
    "Current Manipulator": "电流操纵器",
    "Dark Energy Condenser": "暗能源冷凝器",
    "Design 2.0": "设计2.0",
    "Design overhaul": "设计大修",
    "Dimensional Vortex": "次元漩涡",
    "Dimensional Vortex Improvement": "次元漩涡改善",
    "Energy Collector": "能源收集器",
    "Farm / Upgrades buttons are smaller": "农场/升级按钮更小",
    "FARMS": "农场",
    "Fission Reactor": "裂变反应堆",
    "Fission Reactor Improvement": "裂变反应堆改进",
    "Fusion Reactor": "聚变反应堆",
    "Fusion Reactor Improvement": "聚变反应堆改进",
    "Green per click:": "每次点击绿色：",
    "Green per sec:": "每秒绿色：",
    "Heat Absorber": "吸热器",
    "Hydro Power Station": "水电站",
    "Hydro Power Station Improvement": "水电站改造",
    "Improved Air Bending": "改进的空气弯曲",
    "Improved Current Manipulation": "改进的电流操作",
    "Improved Heat Absorbtion": "改善吸热性",
    "Improved Mathematics": "提高数学",
    "Improved Mind Power": "提高思维能力",
    "Improved Physics": "改进物理",
    "LvL up!": "升级！",
    "Mad Scientist": "疯狂的科学家",
    "New Achievements": "新成就",
    "New Energy": "新能源",
    "Ok": "好的",
    "Orange per click:": "每次点击橙色：",
    "Orange per sec:": "橙色每秒：",
    "Performance improvement": "性能改进",
    "Permanent": "永久",
    "Pink per click:": "粉红色每次点击：",
    "Pink per sec:": "粉红色每秒：",
    "Powerups": "提升",
    "Purchase new energy button added": "添加购买新能源按钮",
    "Purple per click:": "每次点击紫色：",
    "Purple per sec:": "紫色每秒：",
    "Red per click:": "红色每次点击：",
    "Red per sec:": "红色每秒：",
    "Reset Game": "重置游戏",
    "Scientist": "科学家",
    "Solar Plant": "太阳能发电厂",
    "Solar Plant Improvement": "太阳能发电厂改进",
    "Stats": "统计数据",
    "Store page": "商店页面",
    "Teleporter": "传送器",
    "Temporary (Does not affect most recent energy)": "临时（不影响最近的能源）",
    "The Game has now autosave": "游戏现在有自动保存",
    "Total Energy Collected:": "收集的总能源：",
    "Total Energy Converted:": "总能源转换：",
    "Total Energy Currencies:": "总能源货币：",
    "Total Energy Farmed:": "总能源养殖：",
    "Total Farms:": "总农场：",
    "Total Upgrades:": "总升级：",
    "Two new energies": "两种新能源",
    "Upcoming Features": "即将推出的功能",
    "Updates": "更新",
    "UPGRADES": "升级",
    "Wind Turbine": "风力涡轮机",
    "Wind Turbine Improvement": "风力涡轮机改进",
    "Wishlist the upcoming remake on Steam:": "将即将在 Steam 上重制的游戏列入愿望清单：",
    "You can now convert currencies": "您现在可以转换货币",
    "Pay 100 green to unlock a new energy": "支付 100 绿色 解锁一个新能源",
    "Clockwork": "发条装置",
    "Increase spawnrate by 300%": "增加 300% 的产生率",
    "Pay 50000 green and 10000 red to increases XP gain by double": "支付 50000 绿色和 10000 红色以增加双倍的 经验 增益",
    "Shield": "护盾",
    "Power of Nature": "自然之力",
    "The Hammer": "锤子",
    "Armageddon": "世界末日",
    "Battery": "电池",
    "Accepted": "公认",
    "Achievement Whore": "成就婊子",
    "Alchemist": "炼金术士",
    "Allowance Saver": "减免津贴",
    "Almost give up...": "差点放弃...",
    "Apprentice": "学徒",
    "Architect": "建筑师",
    "Baby Steps": "婴儿学步",
    "Beginning Of The Journey": "旅程的开始",
    "Bill Counterfeiter": "票据伪造者",
    "Botter": "博特",
    "City Owner": "城主",
    "Collector": "集电极",
    "Completionist": "完成主义者",
    "Conversion Master": "转换大师",
    "Convertalist": "皈依者",
    "Dedicated": "投入的",
    "Element Creater": "元素创造者",
    "Energy Maniac": "能源狂人",
    "Energy Master": "能源大师",
    "Energyphilia": "能源爱好者",
    "Engineer": "工程师",
    "Environmentalist": "环保主义者",
    "Extremist": "极端主义者",
    "Fanboy": "迷弟",
    "Farmer": "农民",
    "Getting There": "到达那里",
    "Hoarder": "囤积者",
    "Invester": "投资人",
    "Material Enthusiast": "物质爱好者",
    "Nature Enthusiast": "自然爱好者",
    "Noob": "小白",
    "Peasant": "农民",
    "Pick up 10 green in a row.": "连续捡起 10 个绿色。",
    "Pick up 100 green in a row.": "连续捡起 100 个绿色。",
    "Pick up 250 green in a row.": "连续捡起 250 个绿色。",
    "Pick up nothing for 10 hours.": "10 小时内什么也没捡。",
    "Professional": "专业人士",
    "Share Holder": "股东",
    "Slave Owner": "奴隶主",
    "Spoiled": "被宠坏了",
    "Tax Cheater": "税务骗子",
    "The Energy Born": "能源诞生",
    "Tightwad": "吝啬鬼",
    "Troubling Times": "麻烦事",
    "Unemployed": "失业",
    "Ungenerous": "吝啬",
    "Upgradomaniac": "升级狂",
    "Visit our facebook page.": "访问我们的 Facebook 页面。",
    "Wolf Of Wallstreet": "华尔街的狼",
    "World Dominator": "世界霸主",
    "Zen Master": "禅师",
    "Pay 200 red to unlock a new energy": "支付 200 红色解锁一个新能源",
    "Unlock more energies to convert red.": "解锁更多的能源来转换红色。",
    "Green": "绿色",
    "Red": "红色",
    "Black": "黑色",
    "Pink": "粉色",
    "Purple": "紫色",
    "Orange": "橙色",
    "Blue": "蓝色",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "lvl: ": "等级：",
    "Unlock at lvl ": "解锁于等级 ",
    "You Reached Level ": "你达到了等级 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " per click multiplier": "每次点击乘数",
    " per second multiplier": "每秒乘数",
    " per click +1": "每次点击 +1",
    " per second +1": "每秒 +1",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\+([\d\.,]+) Green$/, '+$1 绿色'],
    [/^Gain ([\d\.,]+) achievements.$/, '达成 $1 成就。'],
    [/^You have reached level ([\d\.,]+).$/, '你达到 $1 级。'],
    [/^You have converted a total of ([\d\.,]+) energy.$/, '你总计转换 $1 能源。'],
    [/^You have farmed a total of ([\d\.,]+) energy.$/, '你总计耕耘 $1 能源。'],
    [/^You have collected a total of ([\d\.,]+) energy.$/, '你总计收集 $1 能源。'],
    [/^You have a total of ([\d\.,]+) energy.$/, '你总计拥有 $1 能源。'],
    [/^You have a total of ([\d\.,]+) energies.$/, '你总计拥有 $1 能源。'],
    [/^You have a total of ([\d\.,]+) upgrades.$/, '你总计拥有 $1 升级。'],
    [/^You have a total of ([\d\.,]+) Farms.$/, '你总计拥有 $1 农场。'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);